name: Create Release

on:
    pull_request:
        branches:
            - main
        paths:
            - '!docs/**'
jobs:
    # This workflow contains a single job called "build"
    create-tag:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Get next version
              uses: reecetech/version-increment@2024.10.1
              id: version
              with:
                  scheme: semver
                  increment: patch
                  release_branch: master

            - name: Echo version
              id: echo_version
              env:
                  VERSION: ${{ steps.version.outputs.version }}
              run: |
                  if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-pre\.[a-f0-9]+)?$ ]]; then
                    echo "Invalid version format. Must be semantic version (e.g. 1.2.3 or 1.2.3-pre.abc123)"
                    exit 1
                  fi
                  echo "Version: $VERSION"
