name: Publish to GitHub Packages

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Use Node.js - 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install
              run: npm ci

            - name: Test
              run: npm test

    publish-github-packages:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Use Node.js - 22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@humanspeak'

            - name: Install
              run: npm ci

            - name: Publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
